### ISSUE TITLE
Inventory Script - Interactive Window change colors on error?

### ISSUE THREAD

**Issue by dzellner** [nulib/nul-rdc-scripts#60]
Could the interactive window change colors when you make an error (ex. use a capitol P for project number)?
This would be helpful since the error messages currently appear on a different part of the screen.
This is not critical.

**Comment by SophiaFrancis1** [comment]
I can't at the current moment as there are no ways to control that interactive window (size, color, anything with the UI). That would have to be done on VSCodes end unfortunately.
